trigger:
- developer

pool:
  name: Azure Pipelines

steps:
#- task: AzureCLI@2
#  displayName: 'Azure CLI src/code'
#  inputs:
#    azureSubscription: 'terraform_pipelines'
#    scriptType: 'bash'
#    scriptLocation: 'inlineScript'
#    inlineScript: 'az storage blob download --account-name cuenta1234 --container-name web05 --name dev-env.tfstate --file terraform.tfstate'
#    workingDirectory: src/code    

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/artifacts'
  inputs:
    SourceFolder: src
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts'
    CleanTargetFolder: true

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  displayName: 'Install Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : init'
  inputs:
    workingDirectory: src/code
    backendServiceArm: 'terraform_pipelines'
    backendAzureRmResourceGroupName: 'terraform_pipelines'
    backendAzureRmStorageAccountName: cuenta1234
    backendAzureRmContainerName: web05
    backendAzureRmKey: 'dev-env.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : plan'
  inputs:
    command: plan
    workingDirectory: src/code
    commandOptions: '-var-file="dev.tfvars"'
    environmentServiceNameAzureRM: 'terraform_pipelines'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/artifacts'
    artifact: drop